### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by KORAREO** [jbrillon/compressible-Blasius-solver#2]
Could you please make using Matlab? if possible?

**Comment by jbrillon** [comment]
What exactly do you by 'make' using Matlab?

**Comment by KORAREO** [comment]
I mean the whole process

**Comment by jbrillon** [comment]
Feel free to re-write it in MATLAB if you wish and open a pull request. However I am not planning to develop this code any further, it was written in an open-source language so that it is accessible by everyone. 

If you would like to run it yourself, modify the following lines to set the viscosity model and the desired boundary condition:
https://github.com/jbrillon/compressible-Blasius-solver/blob/26bd12aac0d23370be8258fedb259f52efb76b53/compressibleBlasius.py#L190-L191

Then, to run the code, I believe all you need to do is call `python compressibleBlasius.py`.
